before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X cmd.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
    binary: "{{ .ProjectName }}_v{{ .Version }}"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
changelog:
  skip: true

nfpms:
  - license: MIT
    maintainer: Tom Morelly <tom.morelly@sva.de>
    homepage: https://github.com/FalcSuessgott/golang-cli-template
    bindir: /usr/bin
    description: golang cli template
    formats:
      - deb
      - rpm
