site_name: golang-cli-template
site_description: "A general purpose golang CLI template for Github and Gitlab"
site_author: FalcoSuessgott

repo_name: FalcoSuessgott/vkv
repo_url: https://github.com/FalcoSuessgott/golang-cli-template

docs_dir: docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      locale: en
      enable_creation_date: false

nav: 
  # add here more markdown files recursive under docs/ dir
  - index.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

theme:
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
  name: material
  
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.top
    - navigation.expand
    - navigation.footer