name: Test and coverage

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: go get
        run: go get ./...

      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
